
= getting-started

The `getting-started` project is a simple Jakarta EE application with a HTTP endpoint that is running in 
https://wildfly.org[WildFly].

The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Building the application

To run the application, you use Maven:

[source,shell]
----
mvn clean package
----

Maven will compile the application, provision a WildFly server
The WildFly server is created in `target/server` with the application deployed in it.

== Running the application

To run the application, run the commands:

[source,shell]
----
cd target/server
./bin/standalone.sh
----

Once WildFly is running, the application can be accessed at http://localhost:8080/

== Testing the application

To run integration tests to verify the application, you use Maven:

[source,shell]
----
mvn clean package verify
----

Tests in `src/test` are run against the server in `target/server`.

== Deploying on Kubernetes

We need to create a secret to hold the credentials to be able to upload to the image registry:

[source,shell]
----
kubectl delete secret quay-secret --namespace $user_namespace
kubectl create secret generic quay-secret --namespace $user_namespace --from-literal=IMAGE_REGISTRY_PASSWORD=******** --from-literal=IMAGE_REGISTRY_LOGIN=ehugonne@redhat.com --from-literal=IMAGE_REGISTRY_NAMESPACE=ehugonne
kubectl label secret quay-secret --namespace $user_namespace controller.devfile.io/mount-to-devworkspace=true controller.devfile.io/watch-secret=true
kubectl annotate secret quay-secret --namespace $user_namespace controller.devfile.io/mount-as='env'
----


== Resources

* https://wildfly.org[WildFly]
* https://docs.wildfly.org[WildFly Documentation]
